### ISSUE TITLE
TTS appears to not output if the text is too long

### ISSUE THREAD

**Issue by nikito** [rhasspy/rhasspy3#2]
Hello,
In testing out rhasspy with a few commands via Home Assistant and the addon, I noticed that if the text is long TTS is not outputting replies, though the log shows the full reply and that it was sent to TTS:
`DEBUG:rhasspy3.program:client_unix_socket.py [‘var/run/faster-whisper.socket’]
DEBUG:rhasspy3.program:vad_adapter_raw.py [‘–rate’, ‘16000’, ‘–width’, ‘2’, ‘–channels’, ‘1’, ‘–samples-per-chunk’, ‘512’, ‘script/speech_prob “share/silero_vad.onnx”’]
DEBUG:rhasspy3_http_api.pipeline:stream-to-stream: voice started
DEBUG:rhasspy3_http_api.pipeline:stream-to-stream: voice stopped
INFO:faster_whisper_server: What’s the weather like?
DEBUG:rhasspy3_http_api.pipeline:stream-to-stream: asr=Transcript(text=" What’s the weather like?“)
DEBUG:rhasspy3.program:handle_adapter_text.py [‘bin/converse.py --language “” “http://supervisor/core/api/conversation/process” “/app/config/data/handle/home_assistant/token”’]
DEBUG:rhasspy3.handle:handle: input=Transcript(text=” What’s the weather like?")
DEBUG:rhasspy3.handle:handle: Handled(text=‘Currently the weather is sunny, with a temperature of 43 degrees. Under present weather conditions the temperature feels like 36 degrees. In the next few hours the weather will be more of the same, with a temperature of 43 degrees.’)
DEBUG:rhasspy3_http_api.pipeline:stream-to-stream: handle=Handled(text=‘Currently the weather is sunny, with a temperature of 43 degrees. Under present weather conditions the temperature feels like 36 degrees. In the next few hours the weather will be more of the same, with a temperature of 43 degrees.’)
DEBUG:rhasspy3_http_api.pipeline:stream-to-stream: sending tts
DEBUG:rhasspy3.program:client_unix_socket.py [‘var/run/larynx2.socket’]
Real-time factor: 0.107471 (infer=1.27417 sec, audio=11.856 sec)
DEBUG:rhasspy3_http_api.pipeline:stream-to-stream: tts done`

Not sure if this is an issue with the websocket/larynx, or just the browser not handling the longer stream correctly (was testing the satellite via browser on the addon web UI interface).

In further testing I also noticed that after the request, regardless of TTS length, my dev console gets flooded with this message continuously:
![image](https://user-images.githubusercontent.com/733609/223155250-786830dc-4fc1-4b4c-95d8-2e8d8ca3e6d1.png)

Testing other commands (such as What time is it or What is the date) worked fine and outputted TTS audio.

Thanks!

**Comment by synesthesiam** [comment]
Thanks for catching this! I've pushed an update to the add-on to fix it. Seems like I have to split the chunk up or it won't go through stdin/stdout correctly.

Please re-open if you still have an issue.

**Comment by nikito** [comment]
Just retested with the same scenario, and the behavior is still the same. I'm not getting any TTS back (also on the UI I noticed that I get an audio-start payload but there is no audio-end payload with the TTS as the other test does). I am also still getting flooded with the console error (over 8k and climbing unless I kill the page 🤣 ) not sure if that could be part of the cause? From what I see I think the issue is the recorder stream continues to try and send to the websocket even after it is closed, maybe we just need a check in the recorder.port.onmessage function to check if the websocket.readyState is open, and if it closed to disconnect the recorder? Note this happens in both satellite.html as well as the asr.html. If you want me to open as a separate issue I can do that as well. Thanks!

**Comment by nikito** [comment]
If it helps, I pasted the text from the above into the tts page, and it had no issue generating the output and playing. 😃

**Comment by synesthesiam** [comment]
I made another attempt :slightly_smiling_face: 
I also close the audio recorder when the websocket closes, so hopefully that won't flood your dev console anymore!

**Comment by nikito** [comment]
Thanks, just gave it a try. The error flood is one on both ASR and Satellite page! However I still am not getting TTS for the long text. I do see in the new debug output that is is replying correctly in terms of the payload:
![image](https://user-images.githubusercontent.com/733609/223287960-9cd5d228-18fb-43e8-bb38-bb21027df248.png)
Here's the log output from HA as well:
`DEBUG:rhasspy3.program:client_unix_socket.py ['var/run/faster-whisper.socket']
DEBUG:rhasspy3.program:vad_adapter_raw.py ['--rate', '16000', '--width', '2', '--channels', '1', '--samples-per-chunk', '512', 'script/speech_prob "share/silero_vad.onnx"']
DEBUG:rhasspy3_http_api.pipeline:stream-to-stream: voice started
DEBUG:rhasspy3_http_api.pipeline:stream-to-stream: voice stopped
INFO:faster_whisper_server: How's the weather?
DEBUG:rhasspy3_http_api.pipeline:stream-to-stream: asr=Transcript(text=" How's the weather?")
DEBUG:rhasspy3.program:handle_adapter_text.py ['bin/converse.py --language "" "http://supervisor/core/api/conversation/process" "/app/config/data/handle/home_assistant/token"']
DEBUG:rhasspy3.handle:handle: input=Transcript(text=" How's the weather?")
DEBUG:rhasspy3.handle:handle: Handled(text='Currently the weather is partly cloudy, with a temperature of 42 degrees. Under present weather conditions the temperature feels like 34 degrees. In the next few hours the weather will be  more of the same,  with a temperature of 39 degrees.')
DEBUG:rhasspy3_http_api.pipeline:stream-to-stream: handle=Handled(text='Currently the weather is partly cloudy, with a temperature of 42 degrees. Under present weather conditions the temperature feels like 34 degrees. In the next few hours the weather will be  more of the same,  with a temperature of 39 degrees.')
DEBUG:rhasspy3_http_api.pipeline:stream-to-stream: sending tts
DEBUG:rhasspy3.program:client_unix_socket.py ['var/run/larynx2.socket']
Real-time factor: 0.114883 (infer=1.47785 sec, audio=12.864 sec)
DEBUG:rhasspy3_http_api.pipeline:stream-to-stream: tts done`

I'm working on setting up a dev environment so I can try to dig in as well :)

**Comment by nikito** [comment]
Hi @synesthesiam!
So here's an amusing predicament. I set up my dev environment using the tutorial (went smoothly and very detailed, thanks!), and ran the http server, then did the same test as above. Crazily enough it worked perfectly fine in the browser! So seems the issue is limited to the HA addon itself, but haven't really dug into that (don't have much experience working with the addons unfortunately 😄 ) Hope this at least provides some useful info on troubleshooting.

**Comment by nikito** [comment]
@synesthesiam also just noticed, appears I am not able to make branches against this repo, not sure if that is intentional or not. Was going to make a PR for an enhancement I noticed 😃

**Comment by nikito** [comment]
One more thing I noticed when trying to pinpoint this, seems with the large text the content that comes back is tiny, only 44 bytes:
![image](https://user-images.githubusercontent.com/733609/223547213-b0f38920-ea41-4553-bb10-27837f5484ac.png)
By comparison, if I do a smaller test, such as asking for the date, I get this:
![image](https://user-images.githubusercontent.com/733609/223547390-ace687b3-c92d-47fa-ba3d-25fa62a397f8.png)
Maybe related?
I also had one odd case where I managed to get a TTS reply with the long weather string, but have not been able to get it to happen again. Makes me wonder if maybe there is some sort of socket limitation happening that's getting hung up?

**Comment by nikito** [comment]
One more thing I discovered playing around with this. When running the HA addon, if I change the tts from default (which I believe is larynx2.client) to larynx2 (non client) it then works every time with long or short text. If I use larynx2.client that's when it starts failing. If I run outside HA, even on a less robust laptop, it works fine with client/server setup. Hope this offers more insight. 😊
