### ISSUE TITLE
Small issue in tutorial

### ISSUE THREAD

**Issue by kha84** [rhasspy/rhasspy3#6]
Keep following your [tutorial](https://github.com/rhasspy/rhasspy3/blob/master/docs/tutorial.md), it's like reading a novel of your favorite author. Found a small issue there, I guess:

Instead of 
```
echo 'What time is it?' | script/run bin/handle_handle.py --debug
```
there should be 
```
echo 'what time is it?' | script/run bin/handle_text.py --debug
```

**Comment by synesthesiam** [comment]
Thank you for the feedback and the kind words :)
Fixed!
